### ISSUE TITLE
LOOP value 'outHumidity' 155 outside limits (0.0, 100.0)

### ISSUE THREAD

**Issue by 2E0PGS** [jardiamj/wmII#2]
Continued from Issue: #1 

I now suspect this is related to something surrounding the station because it seems to only happen at certain times of day. Perhaps solar, temperature, nearby RF or human (switching something off) related.

See the following graphs which put me onto this new theory.

![image](https://user-images.githubusercontent.com/15659301/55279998-83acbd80-5317-11e9-9cf6-bdba8e15e5cd.png)

More graph data here: https://aprs.fi/weather/a/2E0PGS-WX

This seems to happen every day at the same times +or- an hour.

**Comment by 2E0PGS** [comment]
![image](https://user-images.githubusercontent.com/15659301/55280030-f6b63400-5317-11e9-9ba9-c6b1ef406a62.png)

**Comment by jardiamj** [comment]
That is a weird behavior, have you checked what value your station shows on
the screen when this happens? I suspect that your Temperature/Humidity
sensor might be faulty, or something is interfering with it since it seems
to happen every day from late evening until the next morning.
How is the inside humidity reading behaving?

Besides these weird readings, is the rest of the driver working well?

Jardi.
